class PlayerEntity {
  playerKey: number;
  playerId: string;
  playerImage: string;
  playerName: string;
  playerNumber: string;
  playerCountry: string;
  playerType: string;
  playerAge: string;
  playerMatchPlayed: string;
  playerGoals: string;
  playerYellowCards: string;
  playerRedCards: string;
  playerInjured: string;
  playerSubstituteOut: string;
  playerSubstitutesOnBench: string;
  playerAssists: string;
  playerBirthdate: string;
  playerIsCaptain: string;
  playerShotsTotal: string;
  playerGoalsConceded: string;
  playerFoulsCommitted: string;
  playerTackles: string;
  playerBlocks: string;
  playerCrossesTotal: string;
  playerInterceptions: string;
  playerClearances: string;
  playerDispossesed: string;
  playerSaves: string;
  playerInsideBoxSaves: string;
  playerDuelsTotal: string;
  playerDuelsWon: string;
  playerDribbleAttempts: string;
  playerDribbleSucc: string;
  playerPenComm: string;
  playerPenWon: string;
  playerPenScored: string;
  playerPenMissed: string;
  playerPasses: string;
  playerPassesAccuracy: string;
  playerKeyPasses: string;
  playerWoodworks: string;
  playerRating: string;

  constructor(data: any) {
    this.playerKey = data.player_key;
    this.playerId = data.player_id;
    this.playerImage = data.player_image;
    this.playerName = data.player_name;
    this.playerNumber = data.player_number;
    this.playerCountry = data.player_country;
    this.playerType = data.player_type;
    this.playerAge = data.player_age;
    this.playerMatchPlayed = data.player_match_played;
    this.playerGoals = data.player_goals;
    this.playerYellowCards = data.player_yellow_cards;
    this.playerRedCards = data.player_red_cards;
    this.playerInjured = data.player_injured;
    this.playerSubstituteOut = data.player_substitute_out;
    this.playerSubstitutesOnBench = data.player_substitutes_on_bench;
    this.playerAssists = data.player_assists;
    this.playerBirthdate = data.player_birthdate;
    this.playerIsCaptain = data.player_is_captain;
    this.playerShotsTotal = data.player_shots_total;
    this.playerGoalsConceded = data.player_goals_conceded;
    this.playerFoulsCommitted = data.player_fouls_committed;
    this.playerTackles = data.player_tackles;
    this.playerBlocks = data.player_blocks;
    this.playerCrossesTotal = data.player_crosses_total;
    this.playerInterceptions = data.player_interceptions;
    this.playerClearances = data.player_clearances;
    this.playerDispossesed = data.player_dispossesed;
    this.playerSaves = data.player_saves;
    this.playerInsideBoxSaves = data.player_inside_box_saves;
    this.playerDuelsTotal = data.player_duels_total;
    this.playerDuelsWon = data.player_duels_won;
    this.playerDribbleAttempts = data.player_dribble_attempts;
    this.playerDribbleSucc = data.player_dribble_succ;
    this.playerPenComm = data.player_pen_comm;
    this.playerPenWon = data.player_pen_won;
    this.playerPenScored = data.player_pen_scored;
    this.playerPenMissed = data.player_pen_missed;
    this.playerPasses = data.player_passes;
    this.playerPassesAccuracy = data.player_passes_accuracy;
    this.playerKeyPasses = data.player_key_passes;
    this.playerWoodworks = data.player_woordworks;
    this.playerRating = data.player_rating;
  }
}

export default PlayerEntity;
